# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: insight.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'insight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinsight.proto\x12\x07insight\"x\n\x07LogItem\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\tsource_ip\x18\x02 \x01(\t\x12\x16\n\x0e\x64\x65stination_ip\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x05\":\n\x0f\x41nalysisSummary\x12\x17\n\x0fprocessed_count\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2I\n\x0bLogAnalyser\x12:\n\nStreamLogs\x12\x10.insight.LogItem\x1a\x18.insight.AnalysisSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'insight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGITEM']._serialized_start=26
  _globals['_LOGITEM']._serialized_end=146
  _globals['_ANALYSISSUMMARY']._serialized_start=148
  _globals['_ANALYSISSUMMARY']._serialized_end=206
  _globals['_LOGANALYSER']._serialized_start=208
  _globals['_LOGANALYSER']._serialized_end=281
# @@protoc_insertion_point(module_scope)
